name: Test

# Make sure these match with the matrix.os values below
env:
  OS_WINDOWS: windows-latest
  OS_MACOS: macos-latest
  # The Ubuntu version must align with the "core" version in electron-builder.json5 in paranext-core
  OS_LINUX: ubuntu-22.04

on:
  push:
    branches: ['main']
  pull_request:
    # The branches below should be a subset of the branches above
    branches: ['main']
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  test:
    name: Build on ${{ matrix.os }}, .Net ${{ matrix.dotnet_version }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # Make sure these match with the env values above
        os: [windows-latest, macos-latest, ubuntu-22.04]
        dotnet_version: [8.0.x]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Read package.json
        id: package_json
        uses: zoexx/github-action-json-file-properties@1.0.6
        with:
          file_path: 'package.json'

      - name: Install Node.js and NPM
        uses: actions/setup-node@v4
        with:
          node-version: ${{ fromJson(steps.package_json.outputs.volta).node }}
          cache: npm

      - name: npm install
        run: npm install

      - name: Install DMG license
        if: ${{ matrix.os == env.OS_MACOS }}
        run: npm install dmg-license

        # npm test
      - name: npm lint
        env:
          # no hardlinks so dependencies are copied
          USE_HARD_LINKS: false
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run lint
        # npm test

      # Enable tmate debugging of manually-triggered workflows if the input option was provided
      - name: Setup tmate session
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
