/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript. DO NOT MODIFY IT BY HAND.
 * Instead, modify the source JSONSchema file, and run json-schema-to-typescript to regenerate this
 * file.
 */

/** A person who has been involved in creating or maintaining this package. */
export type Person = unknown;

/**
 * Data used to create a packaged build of Platform.Bible with modified branding (white label).
 * Where possible, fields fall back to `package.json`.
 */
export interface ProductInfo {
  /** Name used inside the product for various technical things including temp folder name */
  name?: string;
  /** Version number for the product */
  version?: string;
  /** Human-readable "marketing-level" version to call this version of the product e.g. β1 */
  marketingVersion?: string;
  /**
   * Human-readable "marketing-level" version moniker to call this version of the product e.g.
   * Developer Preview
   */
  marketingVersionMoniker?: string;
  /**
   * Short description explaining what the product is. Set to core's `release/app/package.json`
   * `description`. Not sure where this is used.
   */
  description?: string;
  /**
   * Primary creator of this application. Set to core's `release/app/package.json` `author`. Not
   * sure where this is used.
   */
  author?: Person;
  /**
   * Executable name. Will fall back to `package.json`'s `productName` then `name` if not set. See
   * https://www.electron.build/configuration/configuration.html#configuration for more information
   */
  productName?: string;
  /**
   * Short name, to be used in places where the full name is too long. Will fall back to
   * `productName` if not set
   */
  productShortName?: string;
  /**
   * Application ID used with the Operating System. See
   * https://www.electron.build/configuration/configuration.html#configuration for more information
   */
  appId: string;
  /**
   * Copyright statement to go on the executable. See
   * https://www.electron.build/configuration/configuration.html#configuration for more information
   */
  copyright?: string;
  /**
   * Information about how Electron Builder should publish updates and artifacts for this
   * application. See https://www.electron.build/configuration/publish for more information.
   */
  electronBuilderPublish?: unknown;
  build: BuildInfo;
  [k: string]: unknown;
}
/** Information that determines how the application is built */
export interface BuildInfo {
  /** Information about the core repo (`paranext-core`) to clone and build */
  coreRepo: RepoInformation;
  /**
   * Information about multi-extension repos (clones of paranext-multi-extension-template) to clone
   * and package into the build
   */
  extensionRepos: RepoInformation[];
  [k: string]: unknown;
}
/** Information about a git repo to clone, build, and include in the application */
export interface RepoInformation {
  /** The git clone uri for the repo */
  uri: string;
  /** The name of the branch, tag, or commit to pull when cloning the repo. Defaults to `main` */
  branch?: string;
  /** Name of the git repo (for console logging). Defaults to attempting to get it out of `uri` */
  name?: string;
  [k: string]: unknown;
}
